// tailwind.config.js
// eslint-disable-next-line no-undef
module.exports = {
  safelist: [
      'bg-[url(assets/firstborn-powered-helmet.png)]',
      'lg:bg-[url(assets/firstborn-powered-helmetlg.png)]',
      'bg-[url(assets/infensus-x2-assault-helmet.png)]',
      'lg:bg-[url(assets/infensus-x2-assault-helmetlg.png)]',
      'bg-[url(assets/advanced-civilian-helmet.png)]',
      'lg:bg-[url(assets/advanced-civilian-helmetlg.png)]',
      'bg-[url(assets/mt-27.png)]',
      'lg:bg-[url(assets/mt-27lg.png)]',
      'bg-[url(assets/tactical-systems-helmet.png)]',
      'lg:bg-[url(assets/tactical-systems-helmetlg.png)]',
      'bg-[url(assets/locans-defense-helmet.png)]',
      'lg:bg-[url(assets/locans-defense-helmetlg.png)]',
      'bg-[url(assets/locans-ethereal-helmet.png)]',
      'lg:bg-[url(assets/locans-ethereal-helmetlg.png)]',
      'bg-[url(assets/locans-patrol-helmet.png)]',
      'lg:bg-[url(assets/locans-patrol-helmetlg.png)]',
      'bg-[url(assets/locans-pressured-helmet.png)]',
      'lg:bg-[url(assets/locans-pressured-helmetlg.png)]',
      'bg-[url(assets/pythica-special-operations-helmet.png)]',
      'lg:bg-[url(assets/pythica-special-operations-helmetlg.png)]',
      'bg-[url(assets/pythica-mobile-infantry-helmet.png)]',
      'lg:bg-[url(assets/pythica-mobile-infantry-helmetlg.png)]',
      'bg-[url(assets/pythica-s1-helmet.png)]',
      'lg:bg-[url(assets/pythica-s1-helmetlg.png)]',
      'bg-[url(assets/pythica-sustained-battle-helmet.png)]',
      'lg:bg-[url(assets/pythica-sustained-battle-helmetlg.png)]',
      'bg-[url(assets/nanotech-trauma-helmet.png)]',
      'lg:bg-[url(assets/nanotech-trauma-helmetlg.png)]',
      'bg-[url(assets/nanotech-scout-helmet.png)]',
      'lg:bg-[url(assets/nanotech-scout-helmetlg.png)]',
      'bg-[url(assets/nanotech-voltaic-helmet.png)]',
      'lg:bg-[url(assets/nanotech-voltaic-helmetlg.png)]',
      'bg-[url(assets/nanotech-cognizant-helmet.png)]',
      'lg:bg-[url(assets/nanotech-cognizant-helmetlg.png)]',
      'bg-[url(assets/hypobaric-helmet.png)]',
      'lg:bg-[url(assets/hypobaric-helmetlg.png)]',
      'bg-[url(assets/metabolic-helmet.png)]',
      'lg:bg-[url(assets/metabolic-helmetlg.png)]',
      
      
  ],
};